version: "3"
services:
  notifications-services:
    build: 
      context: .
      dockerfile: Dockerfile.notifications
    container_name: notification-services
    command: sh -c "alembic upgrade head && uvicorn src/main:app --port 8004 --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "8004:8004"
    depends_on:
      - notification-postgres
    networks:
      - app-network

  nginx-notification:
    image: nginx
    container_name: nginx-notification
    volumes:
      - ./nginx/any_conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8084:8084"
    depends_on:
      - event-services
    networks:
      - app-network

  notification-postgres:
    image: postgres:14
    container_name: notification-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME_NOTIFICATION}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_notification:/var/lib/postgresql/data
    networks:
      - app-network

  notifications-grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.notifications_grpc_server
    container_name: notifications-grpc-server
    restart: always
    command: sh -c "gunicorn python grpc_server/notifications_service.py"
    ports:
      - "50054:50054"
    networks:
      - app-network

volumes:
  postgres_data_notification:

networks:
  app-network:
    driver: bridge