# Generated by Django 4.2.5 on 2024-11-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    models.TextField(blank=True, verbose_name="Права доступа"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        help_text="Настройки пользователя, связанные с уведомлениями, предпочтениями и т.д.",
                        null=True,
                        verbose_name="Настройки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuestProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temp_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Временный ID"
                    ),
                ),
                ("is_registered", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        max_length=255, verbose_name="Название организации"
                    ),
                ),
                (
                    "organization_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email организации"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Организатор верифицирован"
                    ),
                ),
                (
                    "verified_documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="organizer_docs/",
                        verbose_name="Документы для верификации",
                    ),
                ),
            ],
        ),
    ]
