# Generated by Django 4.2.5 on 2024-11-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizerprofile",
            name="organization_email",
            field=models.EmailField(
                default=True,
                max_length=254,
                unique=True,
                verbose_name="Email организации",
            ),
            preserve_default=False,
        ),
    ]
