# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x1f\n\x11OrgProfileRequest\x12\n\n\x02id\x18\x01 \x01(\t\"z\n\x12OrgProfileResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x11organization_name\x18\x02 \x01(\t\x12\x1a\n\x12organization_email\x18\x03 \x01(\t\x12\x13\n\x0bis_verified\x18\x04 \x01(\x08\x12\x0c\n\x04role\x18\x05 \x01(\t\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"I\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"#\n\x12TokenVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"F\n\x13TokenVerifyResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t2\xb4\x01\n\x0bUserService\x12>\n\x13GetOrganizerProfile\x12\x12.OrgProfileRequest\x1a\x13.OrgProfileResponse\x12&\n\x07GetUser\x12\x0c.UserRequest\x1a\r.UserResponse\x12=\n\x10\x43heckVerifyToken\x12\x13.TokenVerifyRequest\x1a\x14.TokenVerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORGPROFILEREQUEST']._serialized_start=14
  _globals['_ORGPROFILEREQUEST']._serialized_end=45
  _globals['_ORGPROFILERESPONSE']._serialized_start=47
  _globals['_ORGPROFILERESPONSE']._serialized_end=169
  _globals['_USERREQUEST']._serialized_start=171
  _globals['_USERREQUEST']._serialized_end=196
  _globals['_USERRESPONSE']._serialized_start=198
  _globals['_USERRESPONSE']._serialized_end=271
  _globals['_TOKENVERIFYREQUEST']._serialized_start=273
  _globals['_TOKENVERIFYREQUEST']._serialized_end=308
  _globals['_TOKENVERIFYRESPONSE']._serialized_start=310
  _globals['_TOKENVERIFYRESPONSE']._serialized_end=380
  _globals['_USERSERVICE']._serialized_start=383
  _globals['_USERSERVICE']._serialized_end=563
# @@protoc_insertion_point(module_scope)
