version: "3"
services:
  gateway-services:
    build: 
      context: .
      dockerfile: Dockerfile.gateway
    container_name: notification-services
    command: sh -c "uvicorn src/main:app --port 8000 --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx-gateway:
    image: nginx
    container_name: nginx-gateway
    volumes:
      - ./nginx/any_conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - gateway-services
    networks:
      - app-network

networks:
  app-network:
    driver: bridge