# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\"$\n\x10\x45ventByIdRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\"\xf6\x01\n\x11\x45ventByIdResponse\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x12\x10\n\x08location\x18\x06 \x01(\t\x12\x19\n\x11number_of_tickets\x18\x07 \x01(\x05\x12\x11\n\tis_active\x18\x08 \x01(\x08\x12\x14\n\x0corganizer_id\x18\t \x01(\t\x12\x16\n\x0eorganizer_name\x18\n \x01(\t\x12\x17\n\x0forganizer_email\x18\x0b \x01(\t2E\n\x0c\x45ventService\x12\x35\n\x0cGetEventById\x12\x11.EventByIdRequest\x1a\x12.EventByIdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTBYIDREQUEST']._serialized_start=15
  _globals['_EVENTBYIDREQUEST']._serialized_end=51
  _globals['_EVENTBYIDRESPONSE']._serialized_start=54
  _globals['_EVENTBYIDRESPONSE']._serialized_end=300
  _globals['_EVENTSERVICE']._serialized_start=302
  _globals['_EVENTSERVICE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
