# Generated by Django 4.2.5 on 2024-11-27 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="custom_id",
            new_name="id",
        ),
    ]
