FROM python:3.11

WORKDIR /usr/src/app

COPY req.txt ./

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r req.txt

COPY . .

RUN python manage.py collectstatic --noinput
RUN python manage.py makemigrations

CMD ["gunicorn", "python", "grpc_server.py"]
