version: "3"
services:
  booking-services:
    build: 
      context: .
      dockerfile: Dockerfile.booking
    container_name: booking-services
    command: sh -c "alembic upgrade head && uvicorn main:app --port 8002 --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - booking-postgres
    networks:
      - app-network

  nginx-booking:
    image: nginx
    container_name: nginx-booking
    volumes:
      - ./nginx/any_conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:8082"
    depends_on:
      - booking-services
    networks:
      - app-network

  booking-postgres:
    image: postgres:14
    container_name: booking-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME_BOOKING}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_booking:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data_booking:

networks:
  app-network:
    driver: bridge